### ISSUE TITLE
Preset Settings: There are still some inconsinstencies

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-tree-list#104]
<img width="1078" alt="Screenshot 2024-08-27 at 14 32 01" src="https://github.com/user-attachments/assets/898d242b-add7-4c1c-8606-0a7e2122ccc3">
<img width="1078" alt="Screenshot 2024-08-27 at 14 31 40" src="https://github.com/user-attachments/assets/67c5bc6a-9278-444f-b308-d6a26a4895db">
<img width="1082" alt="Screenshot 2024-08-27 at 14 31 32" src="https://github.com/user-attachments/assets/8c1bbd9c-d49d-491a-9a95-477aec476444">

**Comment by christophdb** [comment]
This also happens sometimes if a second level is selected:
![image](https://github.com/user-attachments/assets/6793430d-a225-433a-b680-5c797fbb77f0)

My further analysis shows that the reason might be that the base is broken, not the plugin.
