### ISSUE TITLE
Styling issues in production

### ISSUE THREAD

**Issue by christophdb** [seatable/seatable-plugin-tree-list#124]
All these issues were found in production:

- elements are not correctly aligned (only in production)

![image](https://github.com/user-attachments/assets/05f4e509-0a13-4b4e-80a9-be3c737a82e3)

- no scroll bars at all
- the dark blue hover color in the settings should be changed to #f5f5f5

![image](https://github.com/user-attachments/assets/b46eb377-e6df-4f30-af4f-144ad4e9cf7b)

- add new lines, the input box should be positioned correctly

![image](https://github.com/user-attachments/assets/234787a2-1993-491f-b225-9db16462b086)

- different font sizes for the three levels

see former feedback

- in general: the different levels are not clearly separated from each other. Styling not optimal
- icon and description (I will provide the required text and icon)
- padding on the right like padding on the left (I can not create a screenshot due to missing scrollbars)

**Comment by matteobu** [comment]
@christophdb is this solving the issues?
`in general: the different levels are not clearly separated from each other. Styling not optimal`
and 
`different font sizes for the three levels`

<img width="1091" alt="Screenshot 2024-09-04 at 17 35 54" src="https://github.com/user-attachments/assets/577536c2-74bf-4a3e-9c98-5918b7f86dea">
