### ISSUE TITLE
CSS Styling for collaborator and long text

### ISSUE THREAD

**Issue by christophdb** [seatable/seatable-plugin-tree-list#142]
![image](https://github.com/user-attachments/assets/6af6310c-1b4a-4dc5-bd06-c9c494b3b9a8)

Styling of collaborator and Long-Text columns is not perfect in production.

**Comment by christophdb** [comment]
![image](https://github.com/user-attachments/assets/2f6b85ef-0ab4-4a8a-93d5-1b0b30c53f25)

this css value is also responsible for this styling problem:

![image](https://github.com/user-attachments/assets/d001d2a9-fbbb-4e3f-93f0-4b5f9c23a5d8)

Please check, that this displacement is also fixed.

**Comment by matteobu** [comment]
Fixed and merged
