### ISSUE TITLE
Styling of background

### ISSUE THREAD

**Issue by christophdb** [seatable/seatable-plugin-tree-list#147]
If table relationship plugin and tree plugin is activated in a base, the background of the tree plugin changes.

![image](https://github.com/user-attachments/assets/fe9e9cb9-17b3-4284-815f-7b5899b590ef)

Is it possible to use different class id's for the plugins? It seems that table relationship and tree share the same css class id, which lead to this problems 

![image](https://github.com/user-attachments/assets/0a5bf82c-576e-442b-8176-7e65f9cfd42a)

**Comment by matteobu** [comment]
Yes, we should use a different scss name for each Plugin. 
`PluginTree.module.scss`
