### ISSUE TITLE
PTL: Allow to add new row for each level. (i.e. +add milestone)

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-tree-list#17]
<img width="501" alt="Screenshot 2024-05-26 at 23 56 18" src="https://github.com/seatable/seatable-plugin-tree-list/assets/62759388/aa2f1c23-4162-4893-b341-8f3bc8621598">

**Comment by christophdb** [comment]
In general, this feature works. 
Additional testing required to make sure that adding new lines on every level and with every first column type is possible.
