### ISSUE TITLE
No Scroling Columns

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-tree-list#73]
> I don't like the scrolling inside a column. Also I don't like the fixed with of 200px for every column. If possible, I would allow that the columns are resizable: https://jsfiddle.net/6j10L3x2/1/. The challenge will be that if you change the column width on level 1, all other columns of level 1 should be resized too and you have to persist this value in the preset.

**Comment by matteobu** [comment]
![Uploading Peek 2024-06-28 12-32.gif…]()

**Comment by christophdb** [comment]
tested with commit 87a2345 and resizing is working good.
