### ISSUE TITLE
Link Formula Columns break the plugin

### ISSUE THREAD

**Issue by christophdb** [seatable/seatable-plugin-tree-list#76]
Adding a link formula breaks the plugin

![image](https://github.com/seatable/seatable-plugin-tree-list/assets/7803347/e2a04863-a302-41b1-9363-f154cf348623)

![image](https://github.com/seatable/seatable-plugin-tree-list/assets/7803347/c971752d-4aca-4391-8678-2d5c730058a8)

**Comment by matteobu** [comment]
@christophdb 

I can't reproduce this issue.
In my base, all looks good. 


![Screenshot 2024-07-23 at 12 47 45](https://github.com/user-attachments/assets/d90fa428-dcd6-461a-baa4-2ba2aab34692)

**Comment by christophdb** [comment]
looks like this is fixed.
