### ISSUE TITLE
PTL (UI): Plugin Presets Component behaviour

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-tree-list#81]
The plugin preset component keeps changing width whenever there is an intersection with the tree list.

See the video:

https://github.com/user-attachments/assets/e10366ff-4010-4627-97ae-5cef1e072aed

**Comment by christophdb** [comment]
Tested at 29.08.2024 with branch PTL-104 with commit 87a2345 and the problem is solved.
